import { SareeProduct } from './hanging-card.types';

export const HANGING_CARD_DATASET: SareeProduct[] = [
  {
    id: 'saree-01',
    name: 'Haute Zardozi Maroon Silk',
    material: 'Pure Kanjivaram Silk & 24K Gold Zari',
    price: '₹24,999',
    priceNumber: 24999,
    images: [
      '/assets/sarees/saree-maroon.png',
      '/assets/sarees/saree-kanjivaram.png',
      '/assets/sarees/kanjivaram-detail.png',
    ],
    badges: ['Handwoven', 'New Arrival'],
    isFavorite: false,
    category: 'SILK',
    createdAt: '2026-08-01',
  },
  {
    id: 'saree-02',
    name: 'Heritage Imperial Gold Brocade',
    material: 'Pure Chanderi Tissue Silk',
    price: '₹18,500',
    priceNumber: 18500,
    images: [
      '/assets/sarees/saree-gold.png',
      '/assets/sarees/saree-chanderi.png',
      '/assets/sarees/chanderi-detail.png',
    ],
    badges: ['Limited Edition'],
    isFavorite: false,
    category: 'ZARI',
    createdAt: '2026-07-20',
  },
  {
    id: 'saree-03',
    name: 'Royal Velvet Crimson Drape',
    material: 'Raw Mulberry Silk & Zari',
    price: '₹32,000',
    priceNumber: 32000,
    images: [
      '/assets/sarees/saree-maroon.png',
      '/assets/sarees/saree-banarasi.png',
      '/assets/sarees/banarasi-detail.png',
    ],
    badges: ['Handwoven'],
    isFavorite: false,
    category: 'FESTIVE',
    createdAt: '2026-07-15',
  },
  {
    id: 'saree-04',
    name: 'Champagne Gilded Organza',
    material: 'Pure Handloom Organza Silk',
    price: '₹14,999',
    priceNumber: 14999,
    images: [
      '/assets/sarees/saree-gold.png',
      '/assets/sarees/saree-organza.png',
      '/assets/sarees/organza-detail.png',
    ],
    badges: ['New Arrival'],
    isFavorite: false,
    category: 'NEW ARRIVALS',
    createdAt: '2026-08-05',
  },
  {
    id: 'saree-05',
    name: 'Bespoke Bridal Maroon Jamdani',
    material: 'Banarasi Silk & Fine Gold Thread',
    price: '₹42,500',
    priceNumber: 42500,
    images: [
      '/assets/sarees/saree-maroon.png',
      '/assets/sarees/saree-tussar.png',
      '/assets/sarees/tussar-detail.png',
    ],
    badges: ['Limited Edition', 'Handwoven'],
    isFavorite: false,
    category: 'LIMITED EDITION',
    createdAt: '2026-07-10',
  },
  {
    id: 'saree-06',
    name: 'Vintage Antique Gold Weave',
    material: 'Kora Tussar Silk & Handloom Motif',
    price: '₹21,000',
    priceNumber: 21000,
    images: [
      '/assets/sarees/saree-gold.png',
      '/assets/sarees/saree-paithani.png',
      '/assets/sarees/paithani-detail.png',
    ],
    badges: ['Handwoven'],
    isFavorite: false,
    category: 'HANDWOVEN',
    createdAt: '2026-06-28',
  },
  {
    id: 'saree-07',
    name: 'Deep Obsidian Maroon Tissue',
    material: 'Pure Handloom Tissue Silk',
    price: '₹28,999',
    priceNumber: 28999,
    images: [
      '/assets/sarees/saree-maroon.png',
      '/assets/sarees/saree-gold.png',
    ],
    badges: ['New Arrival'],
    isFavorite: false,
    category: 'NEW ARRIVALS',
    createdAt: '2026-08-08',
  },
  {
    id: 'saree-08',
    name: 'Crown Heritage Gold Swarnachari',
    material: 'Swarnachari Silk with Pure Gold Pallu',
    price: '₹48,000',
    priceNumber: 48000,
    images: [
      '/assets/sarees/saree-gold.png',
      '/assets/sarees/saree-maroon.png',
    ],
    badges: ['Limited Edition'],
    isFavorite: false,
    category: 'ZARI',
    createdAt: '2026-07-02',
  },
];

