import { SareeProduct } from './hanging-card.types';

export const HANGING_CARD_DATASET: SareeProduct[] = [
  {
    id: 'saree-01',
    name: 'Haute Zardozi Maroon Silk',
    material: 'Pure Kanjivaram Silk',
    price: '₹24,999',
    images: ['/assets/sarees/saree-maroon.png', '/assets/sarees/saree-gold.png'],
    badges: ['Handwoven', 'New Arrival'],
    isFavorite: false,
  },
  {
    id: 'saree-02',
    name: 'Heritage Imperial Gold Brocade',
    material: 'Pure Chanderi Tissue Silk',
    price: '₹18,500',
    images: ['/assets/sarees/saree-gold.png', '/assets/sarees/saree-maroon.png'],
    badges: ['Limited Edition'],
    isFavorite: true,
  },
  {
    id: 'saree-03',
    name: 'Royal Velvet Crimson Drape',
    material: 'Raw Mulberry Silk & Zari',
    price: '₹32,000',
    images: ['/assets/sarees/saree-maroon.png', '/assets/sarees/saree-gold.png'],
    badges: ['Handwoven'],
    isFavorite: false,
  },
  {
    id: 'saree-04',
    name: 'Champagne Gilded Organza',
    material: 'Pure Handloom Organza',
    price: '₹14,999',
    images: ['/assets/sarees/saree-gold.png', '/assets/sarees/saree-maroon.png'],
    badges: ['New Arrival'],
    isFavorite: false,
  },
  {
    id: 'saree-05',
    name: 'Bespoke Bridal Maroon Jamdani',
    material: 'Banarasi Silk & Fine Gold Thread',
    price: '₹42,500',
    images: ['/assets/sarees/saree-maroon.png', '/assets/sarees/saree-gold.png'],
    badges: ['Limited Edition', 'Handwoven'],
    isFavorite: false,
  },
  {
    id: 'saree-06',
    name: 'Vintage Antique Gold Weave',
    material: 'Kora Tussar Silk',
    price: '₹21,000',
    images: ['/assets/sarees/saree-gold.png', '/assets/sarees/saree-maroon.png'],
    badges: ['Handwoven'],
    isFavorite: false,
  },
  {
    id: 'saree-07',
    name: 'Deep Obsidian Maroon Tissue',
    material: 'Pure Handloom Tissue Silk',
    price: '₹28,999',
    images: ['/assets/sarees/saree-maroon.png', '/assets/sarees/saree-gold.png'],
    badges: ['New Arrival'],
    isFavorite: false,
  },
  {
    id: 'saree-08',
    name: 'Crown Heritage Gold Swarnachari',
    material: 'Swarnachari Silk with Pure Gold Pallu',
    price: '₹48,000',
    images: ['/assets/sarees/saree-gold.png', '/assets/sarees/saree-maroon.png'],
    badges: ['Limited Edition'],
    isFavorite: true,
  },
];
