/**
 * exclusive.service.ts
 *
 * Server-side service for fetching products assigned to the "Exclusive
 * Collection" Wix Catalog V3 category.
 *
 * API strategy (avoids CATALOG_V3_CALLING_CATALOG_V1_API error):
 *  1. @wix/categories queryCategories  — V3 Categories API to find the
 *     category ID by slug.
 *  2. @wix/categories listItemsInCategory — V3 Categories API to get product
 *     IDs in the admin-configured drag-and-drop order.
 *  3. wixClient.products (V1 Products API) to load full product data by ID.
 *     We only call V1 here — the categories step is pure V3, so there is no
 *     cross-version conflict.
 *  4. mapWixProduct() — same mapper used by the Collections page.
 *
 * Cache: 60-second in-memory TTL so admin changes appear within ~1 minute.
 */

import { wixClient, wixCategoriesClient } from './wix';
import { mapWixProduct } from './product.service';
import type { SareeProduct } from '@/features/collections/components/hanging-card.types';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Slug of the Wix category the admin must create:
 *   Name:  "Exclusive Collection"
 *   Slug:  "exclusive-collection"  (auto-generated by Wix)
 */
export const EXCLUSIVE_CATEGORY_SLUG = 'exclusive-collection';

/**
 * treeReference.appNamespace required by the Categories API for Wix Stores.
 */
const WIX_STORES_APP_NAMESPACE = '@wix/stores';

/**
 * appId for Wix Stores — required when filtering items from listItemsInCategory.
 * Fixed identifier documented in the Wix Categories API.
 */
const WIX_STORES_APP_ID = '215238eb-22a5-4c36-9e7b-e7c08025e04e';

// ---------------------------------------------------------------------------
// In-memory cache (60 s TTL)
// ---------------------------------------------------------------------------

const CACHE_TTL_MS = 60_000;

interface CacheEntry {
  data: SareeProduct[];
  timestamp: number;
}

let exclusiveCache: CacheEntry | null = null;

// ---------------------------------------------------------------------------
// Helper: extract plain text from an additionalInfoSection description
// (Wix returns these as rich HTML / rich content)
// ---------------------------------------------------------------------------
function extractPlainText(html: string | undefined | null): string {
  if (!html) return '';
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&nbsp;/g, ' ')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ')
    .trim();
}

// ---------------------------------------------------------------------------
// Helper: find an additionalInfoSection by title (case-insensitive)
// ---------------------------------------------------------------------------
function findInfoSection(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  product: any,
  sectionTitle: string,
): string | null {
  const sections: { title?: string; description?: string }[] =
    product?.additionalInfoSections ?? [];
  for (const sec of sections) {
    if (sec.title?.toLowerCase().trim() === sectionTitle.toLowerCase().trim()) {
      const plain = extractPlainText(sec.description);
      return plain || null;
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Fetches products assigned to the Wix "Exclusive Collection" category.
 *
 * Returns [] (without throwing) when:
 *  - the category has not been created in Wix yet
 *  - the category has 0 visible products
 *  - any Wix API call fails
 */
export async function getExclusiveProducts(): Promise<SareeProduct[]> {
  const now = Date.now();
  if (exclusiveCache && now - exclusiveCache.timestamp < CACHE_TTL_MS) {
    return exclusiveCache.data;
  }

  try {
    // ── Step 1: Locate the "Exclusive Collection" category by slug ───────────
    const catResult = await wixCategoriesClient.categories
      .queryCategories({
        treeReference: { appNamespace: WIX_STORES_APP_NAMESPACE },
      })
      .eq('slug', EXCLUSIVE_CATEGORY_SLUG)
      .limit(1)
      .find();

    if (catResult.items.length === 0) {
      console.warn(
        '[exclusive.service] Wix category "Exclusive Collection" ' +
          `(slug: "${EXCLUSIVE_CATEGORY_SLUG}") not found. ` +
          'Create it in Wix dashboard → Catalog → Categories and assign products.',
      );
      exclusiveCache = { data: [], timestamp: now };
      return [];
    }

    const categoryId = catResult.items[0]._id!;

    // ── Step 2: Get product IDs in admin drag-and-drop order ─────────────────
    const itemsResult = await wixCategoriesClient.categories.listItemsInCategory(
      categoryId,
      { appNamespace: WIX_STORES_APP_NAMESPACE },
      {
        useCategoryArrangement: true,
        cursorPaging: { limit: 50 },
      },
    );

    const orderedProductIds: string[] = (itemsResult.items ?? [])
      .filter(
        (item) =>
          item.appId === WIX_STORES_APP_ID &&
          typeof item.catalogItemId === 'string' &&
          item.catalogItemId.length > 0,
      )
      .map((item) => item.catalogItemId as string);

    if (orderedProductIds.length === 0) {
      exclusiveCache = { data: [], timestamp: now };
      return [];
    }

    // ── Step 3: Fetch full product data via V1 Products API ──────────────────
    // We use wixClient.products.getProduct() (V1) for each product ID.
    // The .hasSome('_id', ids) filter is NOT supported by the Wix V1 backend
    // (it maps _id → entityId internally and rejects $hasSome). Individual
    // getProduct calls are reliable and respect the same auth context.
    // Note: getProduct returns { product: Product } — unwrap the .product field.
    const productResponses = await Promise.all(
      orderedProductIds.map((id) =>
        wixClient.products.getProduct(id).catch(() => null),
      ),
    );

    // Build id→rawProduct map to restore admin order after fetch
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const productMap = new Map<string, any>(
      productResponses
        .filter((r) => r?.product?._id)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .map((r: any) => [r.product._id as string, r.product]),
    );

    // ── Step 4: Map to SareeProduct preserving category order ────────────────
    const mapped: SareeProduct[] = [];

    for (const id of orderedProductIds) {
      const rawProduct = productMap.get(id);
      if (!rawProduct) continue;
      if (rawProduct.visible === false) continue;

      const base = mapWixProduct(rawProduct);

      // Override origin / fabric from Wix product info sections if available.
      // If the admin has not set these sections, the fields inferred by
      // mapWixProduct are used — never a placeholder string.
      const originOverride = findInfoSection(rawProduct, 'Origin');
      const fabricOverride = findInfoSection(rawProduct, 'Fabric');

      mapped.push({
        ...base,
        ...(originOverride ? { origin: originOverride } : {}),
        ...(fabricOverride ? { material: fabricOverride } : {}),
      });
    }

    exclusiveCache = { data: mapped, timestamp: now };
    return mapped;
  } catch (err) {
    console.warn('[exclusive.service] Failed to fetch exclusive products:', err);
    // Serve stale cache on error; hide section if cache is cold.
    if (exclusiveCache) return exclusiveCache.data;
    return [];
  }
}
